name: Close Waiting for Response Issues
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:
jobs:
  check-need-info:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: close-issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const days = 14;
            const msInDay = 24 * 60 * 60 * 1000;
            const thresholdDate = new Date(Date.now() - days * msInDay);

            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'Waiting for Response',
              per_page: 100,
            });

            for (const issue of issues) {
              if (issue.pull_request) continue;
              
              const updatedAt = new Date(issue.updated_at);
              if (updatedAt < thresholdDate) {
                console.log(`Closing issue #${issue.number} as it has been inactive since ${issue.updated_at}`);
                
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: `We are closing this issue because we did not hear back regarding additional details we needed to resolve this issue. If the issue persists and you are able to provide the missing clarification we need, you can respond here or create a new issue.

We appreciate your understanding as we try to manage our number of open issues.`
                });
                
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed',
                  state_reason: 'not_planned'
                });
              }
            }
